# Generated by Django 3.2.7 on 2021-10-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChekList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='status',
            field=models.CharField(choices=[('saturday', 'SATURDAY'), ('sunday', 'SUNDAY'), ('monday', 'Mondaye'), ('tuesday', 'THUESDAYE'), ('wednesday', 'WEDNSEDAY'), ('thursday', 'THURSDAY'), ('friday', 'FRIDAY')], max_length=10),
        ),
    ]
