# Generated by Django 3.2.7 on 2021-10-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChekList', '0003_alter_archive_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='report',
            old_name='subtitlr',
            new_name='subtitle',
        ),
    ]
