# Generated by Django 3.2.7 on 2021-10-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChekList', '0004_auto_20211031_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='category',
            field=models.IntegerField(),
        ),
    ]
